export const environment = {
    production: true,
    baseUrlProd: 'http://spring-security-api-prod.eba-ismfpaip.ap-south-1.elasticbeanstalk.com/api',
    baseUrlDev: 'http://localhost:5000/api',
    signUp: '/auth/register',
    confirmAccount: '/auth/confirm-account',
    resendVerificationToken:'/auth/verification-token',
    resetPasswordToken: '/auth/reset-password',
    resetPassword: '/auth/reset-password/token',
    forgetPasswordToken: '/auth/forget-password',
    forgetPassword: '/auth/forget-password/token',
    login: '/auth/login',
    users: '/user',
    getUser: '/user/',
    getUserById: '/user/userId/',
    getUserByEmail: '/user/email/',
    createPost: '/post/create',
    getPostOfUser: '/post/user/userId/',
    getAllPost: '/post/all',
    addComment: '/comment/create',
    updateComment: '/comment/update',
    deleteComment: '/comment/delete'
}
